/* automatically generated by rust-bindgen */

use libc::*;
use xlib::{Display, Drawable, Visual, Screen, Pixmap};
use cairo::cairo_surface_t;

#[link_name="cairo"]
extern mod bindgen {

fn cairo_xlib_surface_create(++arg0: *Display, ++arg1: Drawable, ++arg2: *Visual, ++arg3: c_int, ++arg4: c_int) -> *cairo_surface_t;

fn cairo_xlib_surface_create_for_bitmap(++arg0: *Display, ++arg1: Pixmap, ++arg2: *Screen, ++arg3: c_int, ++arg4: c_int) -> *cairo_surface_t;

fn cairo_xlib_surface_set_size(++arg0: *cairo_surface_t, ++arg1: c_int, ++arg2: c_int);

fn cairo_xlib_surface_set_drawable(++arg0: *cairo_surface_t, ++arg1: Drawable, ++arg2: c_int, ++arg3: c_int);

fn cairo_xlib_surface_get_display(++arg0: *cairo_surface_t) -> *Display;

fn cairo_xlib_surface_get_drawable(++arg0: *cairo_surface_t) -> Drawable;

fn cairo_xlib_surface_get_screen(++arg0: *cairo_surface_t) -> *Screen;

fn cairo_xlib_surface_get_visual(++arg0: *cairo_surface_t) -> *Visual;

fn cairo_xlib_surface_get_depth(++arg0: *cairo_surface_t) -> c_int;

fn cairo_xlib_surface_get_width(++arg0: *cairo_surface_t) -> c_int;

fn cairo_xlib_surface_get_height(++arg0: *cairo_surface_t) -> c_int;

}
